# Generated by Django 6.0.1 on 2026-01-14 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_classroom', '0002_classjointoken_virtualattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualattendance',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='virtualattendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtualattendance',
            name='virtual_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='virtual_classroom.virtualclass'),
        ),
        migrations.AlterField(
            model_name='virtualclass',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Jitsi meeting link for the class', null=True),
        ),
    ]
